
-- First, let's clear any existing data and insert proper sample projects
DELETE FROM project_enquiries;
DELETE FROM projects;

-- Insert 6 sample projects with proper categories and all required fields
INSERT INTO projects (
  title, subtitle, client_name, status, type, overview, objectives, highlights,
  location, completion_date, unit_types, unit_sizes, cta_title, cta_subtitle,
  button_text, button_link, gallery_images, timeline_steps, client_feedback,
  hero_section, project_info_stats, project_detail_section, amenities_section,
  nearby_locations_section, specifications_section, floor_plans_section,
  gallery_section, brochure_section
) VALUES 
(
  'JKB Sathya Residency',
  'Premium Residential Complex',
  'JKB Constructions',
  ARRAY['Ongoing'],
  'residential',
  'JKB Sathya Residency is a premium residential complex located in the heart of Chennai, offering modern amenities and luxurious living spaces.',
  'To create a sustainable and comfortable living environment with world-class amenities.',
  ARRAY['24/7 Security', 'Swimming Pool', 'Gym', 'Children Play Area', 'Garden'],
  'Valasaravakkam, Chennai',
  '2025-12-31T00:00:00Z',
  '2 BHK, 3 BHK',
  '1200-1800 sq ft',
  'Your Dream Home Awaits',
  'Experience luxury living at its finest',
  'Book Now',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop'],
  '[{"title": "Foundation", "status": "completed", "description": "Foundation work completed", "duration": "3", "unit": "months"}]'::jsonb,
  '{"name": "Rajesh Kumar", "designation": "Director", "company": "Tech Solutions", "testimonial": "Excellent quality construction and timely delivery.", "rating": 5}'::jsonb,
  '{"heading": "JKB Sathya Residency", "description": "Premium living in Chennai", "location": "Valasaravakkam, Chennai", "main_image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Total Units", "value": "120"}, {"label": "Floors", "value": "12"}, {"label": "Parking", "value": "150"}]'::jsonb,
  '{"heading": "About This Project", "description": "Modern residential complex with premium amenities", "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "World-Class Amenities", "description": "Experience luxury with our premium amenities", "amenities": ["Swimming Pool", "Gymnasium", "Children Play Area", "24/7 Security", "Power Backup", "Landscaped Gardens"]}'::jsonb,
  '{"heading": "Prime Location Benefits", "description": "Strategically located with excellent connectivity", "categories": [{"heading": "Educational", "icon": "🏫", "places": [{"name": "Chennai Public School", "distance": "500m"}, {"name": "Anna University", "distance": "2km"}]}, {"heading": "Healthcare", "icon": "🏥", "places": [{"name": "Apollo Hospital", "distance": "1km"}, {"name": "Fortis Hospital", "distance": "1.5km"}]}]}'::jsonb,
  '{"heading": "Technical Specifications", "specifications": [{"subheading": "Structure", "content": "RCC framed structure with seismic resistance"}, {"subheading": "Flooring", "content": "Vitrified tiles in living areas, ceramic tiles in bathrooms"}]}'::jsonb,
  '{"heading": "Floor Plans", "description": "Thoughtfully designed layouts", "floor_plans": [{"title": "2 BHK", "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&h=400&fit=crop", "area": "1200 sq ft", "bedrooms": "2"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Get detailed project information", "brochure_url": "#"}'::jsonb
),
(
  'JKB Commercial Plaza',
  'Modern Business Hub',
  'JKB Developers',
  ARRAY['Completed'],
  'commercial',
  'A state-of-the-art commercial complex designed for modern businesses with premium office spaces and retail outlets.',
  'To provide world-class commercial infrastructure for growing businesses.',
  ARRAY['Central AC', 'High-speed Elevators', 'Ample Parking', 'Food Court', 'Conference Halls'],
  'T Nagar, Chennai',
  '2024-06-30T00:00:00Z',
  'Office Spaces, Retail Outlets',
  '500-2000 sq ft',
  'Prime Commercial Space',
  'Grow your business with us',
  'Enquire Now',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'],
  '[{"title": "Construction", "status": "completed", "description": "Construction completed successfully", "duration": "18", "unit": "months"}]'::jsonb,
  '{"name": "Priya Sharma", "designation": "CEO", "company": "Digital Marketing Agency", "testimonial": "Perfect location and excellent infrastructure for our business.", "rating": 5}'::jsonb,
  '{"heading": "JKB Commercial Plaza", "description": "Premier business destination", "location": "T Nagar, Chennai", "main_image": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Total Area", "value": "2.5 Lakh sq ft"}, {"label": "Floors", "value": "15"}, {"label": "Parking", "value": "300"}]'::jsonb,
  '{"heading": "About This Project", "description": "Modern commercial complex in prime location", "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "Business Amenities", "description": "Everything you need for business success", "amenities": ["Central Air Conditioning", "High-speed Elevators", "24/7 Security", "Power Backup", "Conference Rooms", "Food Court"]}'::jsonb,
  '{"heading": "Strategic Location", "description": "Located in the heart of business district", "categories": [{"heading": "Transportation", "icon": "🚇", "places": [{"name": "T Nagar Metro Station", "distance": "200m"}, {"name": "Chennai Central", "distance": "5km"}]}, {"heading": "Banks", "icon": "🏦", "places": [{"name": "HDFC Bank", "distance": "100m"}, {"name": "SBI Branch", "distance": "150m"}]}]}'::jsonb,
  '{"heading": "Building Specifications", "specifications": [{"subheading": "HVAC", "content": "Central air conditioning with VRV system"}, {"subheading": "Elevators", "content": "High-speed passenger and service elevators"}]}'::jsonb,
  '{"heading": "Space Layouts", "description": "Flexible office configurations", "floor_plans": [{"title": "Office Space", "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=400&fit=crop", "area": "1000 sq ft", "bedrooms": "Open Plan"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Commercial space details", "brochure_url": "#"}'::jsonb
),
(
  'JKB Mixed Development',
  'Integrated Lifestyle Complex',
  'JKB Infrastructure',
  ARRAY['Planning'],
  'mixed use',
  'An innovative mixed-use development combining residential, commercial, and retail spaces in a single integrated complex.',
  'To create a self-sufficient community with residential, commercial, and entertainment facilities.',
  ARRAY['Integrated Complex', 'Shopping Mall', 'Residential Towers', 'Office Spaces', 'Entertainment Zone'],
  'OMR, Chennai',
  '2027-03-31T00:00:00Z',
  'Residential, Commercial, Retail',
  '800-3000 sq ft',
  'Live, Work, Shop, Play',
  'All in one destination',
  'Register Interest',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop'],
  '[{"title": "Planning", "status": "current", "description": "Design and approval phase", "duration": "12", "unit": "months"}]'::jsonb,
  '{"name": "Amit Patel", "designation": "Investor", "company": "Patel Holdings", "testimonial": "Excited about this innovative mixed-use concept.", "rating": 5}'::jsonb,
  '{"heading": "JKB Mixed Development", "description": "Future of integrated living", "location": "OMR, Chennai", "main_image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Total Area", "value": "15 Acres"}, {"label": "Towers", "value": "8"}, {"label": "Units", "value": "500+"}]'::jsonb,
  '{"heading": "About This Project", "description": "Revolutionary mixed-use development", "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "Integrated Amenities", "description": "Complete lifestyle solution", "amenities": ["Shopping Mall", "Multiplex Cinema", "Restaurants", "Gym & Spa", "Swimming Pool", "Business Center"]}'::jsonb,
  '{"heading": "Connectivity Advantage", "description": "Well-connected to major destinations", "categories": [{"heading": "IT Hubs", "icon": "💼", "places": [{"name": "DLF IT Park", "distance": "2km"}, {"name": "Siruseri IT Park", "distance": "5km"}]}, {"heading": "Recreation", "icon": "🎯", "places": [{"name": "Phoenix MarketCity", "distance": "3km"}, {"name": "ECR Beach", "distance": "8km"}]}]}'::jsonb,
  '{"heading": "Development Specifications", "specifications": [{"subheading": "Master Planning", "content": "Integrated development with optimal space utilization"}, {"subheading": "Sustainability", "content": "Green building features with rainwater harvesting"}]}'::jsonb,
  '{"heading": "Unit Configurations", "description": "Diverse space options", "floor_plans": [{"title": "Mixed Use", "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop", "area": "Variable", "bedrooms": "Multiple Options"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Mixed-use development details", "brochure_url": "#"}'::jsonb
),
(
  'JKB Industrial Park',
  'Modern Manufacturing Hub',
  'JKB Industrial Solutions',
  ARRAY['Ongoing'],
  'industrial',
  'A modern industrial park designed for manufacturing and logistics operations with state-of-the-art infrastructure.',
  'To provide world-class industrial infrastructure for manufacturing and logistics companies.',
  ARRAY['Large Plot Sizes', 'Heavy Vehicle Access', 'Power Backup', 'Water Treatment', 'Security'],
  'Sriperumbudur, Chennai',
  '2026-09-30T00:00:00Z',
  'Industrial Plots, Warehouses',
  '5000-50000 sq ft',
  'Industrial Excellence',
  'Setup your manufacturing unit',
  'Contact Us',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&h=600&fit=crop'],
  '[{"title": "Infrastructure", "status": "current", "description": "Basic infrastructure development", "duration": "8", "unit": "months"}]'::jsonb,
  '{"name": "Ravi Krishnan", "designation": "General Manager", "company": "Manufacturing Corp", "testimonial": "Excellent industrial infrastructure with modern facilities.", "rating": 4}'::jsonb,
  '{"heading": "JKB Industrial Park", "description": "Modern manufacturing destination", "location": "Sriperumbudur, Chennai", "main_image": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Total Area", "value": "100 Acres"}, {"label": "Plots", "value": "50"}, {"label": "Industries", "value": "25+"}]'::jsonb,
  '{"heading": "About This Project", "description": "State-of-the-art industrial infrastructure", "image": "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "Industrial Facilities", "description": "Complete industrial ecosystem", "amenities": ["24/7 Power Supply", "Water Treatment Plant", "Waste Management", "Security Systems", "Heavy Vehicle Access", "Fire Safety"]}'::jsonb,
  '{"heading": "Strategic Industrial Location", "description": "Prime location for manufacturing", "categories": [{"heading": "Logistics", "icon": "🚛", "places": [{"name": "Chennai Port", "distance": "25km"}, {"name": "Highway Access", "distance": "1km"}]}, {"heading": "Transportation", "icon": "🚄", "places": [{"name": "Railway Station", "distance": "5km"}, {"name": "Airport", "distance": "15km"}]}]}'::jsonb,
  '{"heading": "Infrastructure Specifications", "specifications": [{"subheading": "Power", "content": "Dedicated 11KV power supply with backup generators"}, {"subheading": "Roads", "content": "Internal concrete roads suitable for heavy vehicles"}]}'::jsonb,
  '{"heading": "Plot Layouts", "description": "Various plot sizes available", "floor_plans": [{"title": "Industrial Plot", "image": "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop", "area": "10000 sq ft", "bedrooms": "Open Space"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Industrial park details", "brochure_url": "#"}'::jsonb
),
(
  'JKB Green Homes',
  'Eco-Friendly Residential Community',
  'JKB Eco Developments',
  ARRAY['Upcoming'],
  'residential',
  'An eco-friendly residential community featuring sustainable construction, solar power, and green living spaces.',
  'To create an environmentally sustainable residential community with modern amenities.',
  ARRAY['Solar Power', 'Rainwater Harvesting', 'Organic Garden', 'EV Charging', 'Green Building'],
  'Tambaram, Chennai',
  '2026-12-31T00:00:00Z',
  '2 BHK, 3 BHK, 4 BHK',
  '1100-2200 sq ft',
  'Green Living Redefined',
  'Sustainable homes for future',
  'Pre-Register',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop'],
  '[{"title": "Approval", "status": "upcoming", "description": "Awaiting final approvals", "duration": "6", "unit": "months"}]'::jsonb,
  '{"name": "Dr. Meera Reddy", "designation": "Environmental Scientist", "company": "Green Tech Institute", "testimonial": "Impressed by the commitment to sustainable development.", "rating": 5}'::jsonb,
  '{"heading": "JKB Green Homes", "description": "Sustainable living community", "location": "Tambaram, Chennai", "main_image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Green Units", "value": "200"}, {"label": "Solar Capacity", "value": "500 KW"}, {"label": "Green Cover", "value": "60%"}]'::jsonb,
  '{"heading": "About This Project", "description": "Eco-friendly residential community", "image": "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "Sustainable Amenities", "description": "Green living at its best", "amenities": ["Solar Power System", "Rainwater Harvesting", "Organic Garden", "EV Charging Stations", "Waste Segregation", "Green Building Materials"]}'::jsonb,
  '{"heading": "Eco-Friendly Location", "description": "Surrounded by natural beauty", "categories": [{"heading": "Nature", "icon": "🌳", "places": [{"name": "Tambaram Lake", "distance": "1km"}, {"name": "Forest Reserve", "distance": "3km"}]}, {"heading": "Utilities", "icon": "⚡", "places": [{"name": "Solar Plant", "distance": "On-site"}, {"name": "Water Treatment", "distance": "On-site"}]}]}'::jsonb,
  '{"heading": "Green Building Specifications", "specifications": [{"subheading": "Energy", "content": "100% solar powered with grid backup system"}, {"subheading": "Materials", "content": "Eco-friendly construction materials with low carbon footprint"}]}'::jsonb,
  '{"heading": "Green Home Plans", "description": "Sustainable home designs", "floor_plans": [{"title": "Eco Home", "image": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop", "area": "1500 sq ft", "bedrooms": "3"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Green homes project details", "brochure_url": "#"}'::jsonb
),
(
  'JKB Heritage Towers',
  'Luxury High-Rise Living',
  'JKB Premium Developers',
  ARRAY['Completed'],
  'residential',
  'A luxury high-rise residential complex offering premium amenities and panoramic city views in the heart of Chennai.',
  'To deliver luxury living with world-class amenities and architectural excellence.',
  ARRAY['Panoramic Views', 'Concierge Service', 'Sky Lounge', 'Premium Interiors', 'Valet Parking'],
  'Nungambakkam, Chennai',
  '2024-03-31T00:00:00Z',
  '3 BHK, 4 BHK, Penthouse',
  '1800-4000 sq ft',
  'Luxury Redefined',
  'Experience elite living',
  'View Gallery',
  '/contact',
  ARRAY['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop'],
  '[{"title": "Handover", "status": "completed", "description": "Project successfully completed and handed over", "duration": "24", "unit": "months"}]'::jsonb,
  '{"name": "Suresh Iyer", "designation": "Senior Executive", "company": "Multinational Corp", "testimonial": "Absolutely stunning project with unmatched luxury and quality.", "rating": 5}'::jsonb,
  '{"heading": "JKB Heritage Towers", "description": "Pinnacle of luxury living", "location": "Nungambakkam, Chennai", "main_image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop"}'::jsonb,
  '[{"label": "Towers", "value": "2"}, {"label": "Floors", "value": "25"}, {"label": "Luxury Units", "value": "180"}]'::jsonb,
  '{"heading": "About This Project", "description": "Luxury high-rise with premium amenities", "image": "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop"}'::jsonb,
  '{"heading": "Luxury Amenities", "description": "Unparalleled luxury experiences", "amenities": ["Sky Lounge", "Infinity Pool", "Private Gym", "Concierge Service", "Valet Parking", "Home Automation"]}'::jsonb,
  '{"heading": "Prime Nungambakkam Location", "description": "Heart of Chennai business district", "categories": [{"heading": "Business", "icon": "🏢", "places": [{"name": "Express Avenue", "distance": "2km"}, {"name": "Business District", "distance": "1km"}]}, {"heading": "Culture", "icon": "🎭", "places": [{"name": "Music Academy", "distance": "1.5km"}, {"name": "Art Gallery", "distance": "800m"}]}]}'::jsonb,
  '{"heading": "Luxury Specifications", "specifications": [{"subheading": "Interiors", "content": "Premium imported marble flooring and designer fixtures"}, {"subheading": "Technology", "content": "Smart home automation with IoT integration"}]}'::jsonb,
  '{"heading": "Luxury Floor Plans", "description": "Spacious and elegant layouts", "floor_plans": [{"title": "Penthouse", "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop", "area": "4000 sq ft", "bedrooms": "4+Study"}]}'::jsonb,
  '{"images": ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop"]}'::jsonb,
  '{"heading": "Download Brochure", "description": "Luxury project details", "brochure_url": "#"}'::jsonb
);
