// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmxpdoljxixqubymyygh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteHBkb2xqeGl4cXVieW15eWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDM1ODgsImV4cCI6MjA2NTAxOTU4OH0.lnQhDwSE4UJeHRw9UzMCQ8BCcCF7ey7Q733ZSeoZ9ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);